force_cast: error
force_try: error

line_length:
  warning: 220
  error: 300

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 40
  error: 140

variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 2
    
opt_in_rules:
  - empty_count
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet

disabled_rules:
  - trailing_whitespace
  - private_outlet
  - private_action

line_length:
  ignores_comments: true

excluded:
  - Pods
