force_cast: error
force_try: error

line_length:
  warning: 220
  error: 300

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 40
  error: 140

opt_in_rules:
  - empty_count
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet

disabled_rules:
  - trailing_whitespace

line_length:
  ignores_comments: true

excluded:
  - Pods
