language: swift
xcode_project: PhotoMap.xcworkspase # path to your xcodeproj folder
xcode_scheme: PhotoMap
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 12
podfile: Podfile
script:
 - swiftlint
 - xcodebuild test -workspace 'PhotoMap.xcworkspase' -scheme 'PhotoMap' -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 12'
